
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/kmontes198910/config_servise
          search-paths: config-data
  application:
    name: config-service
eureka:
  instance:
    hostname: registry
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka