apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasper-init-home
  namespace: medinec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasper-keystore
  namespace: medinec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
