apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-report
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: report
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-report
    spec:
      containers:
        - name: report
          image: kmontes2020/medinec-report:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9908
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: report-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always