apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-calendar
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: calendar
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-calendar
    spec:
      containers:
        - name: calendar
          image: kmontes2020/medinec-calendar:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9908
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: calendar-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always