apiVersion: apps/v1
kind: Deployment
metadata:
  name: jasperserver
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jasperserver
  template:
    metadata:
      labels:
        app: jasperserver
    spec:
      containers:
        - name: jasperserver
          image: agois/jasperserver-ce:7.8.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: jasperreports-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: jasperreports-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: jasperreports-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: jasperreports-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jasperreports-secrets
                  key: DB_PASS
            - name: JRS_DBCONFIG_REGEN
              value: "true"
          command: ["/entrypoint-ce.sh", "run"]
          volumeMounts:
            - name: jasper-webapp
              mountPath: /usr/local/tomcat/webapps/jasperserver
            - name: jasper-home
              mountPath: /usr/local/share/jasperserver
              # Mount the init home directory
            - name: jasper-init-home
              mountPath: /usr/local/share/jasperserver-init
            - name: jasper-license
              mountPath: /usr/local/share/jasperserver/license
            - name: jasper-keystore
              mountPath: /usr/local/share/jasperserver/keystore
            - name: jasper-customization
              mountPath: /usr/local/share/jasperserver/customization
      volumes:
        - name: jasper-webapp
          persistentVolumeClaim:
            claimName: jasper-webapp-pvc
        - name: jasper-home
          persistentVolumeClaim:
            claimName: jasper-home-pvc
        # Definition for the init home PVC
        - name: jasper-init-home
          persistentVolumeClaim:
            claimName: jasper-init-home
        - name: jasper-license
          persistentVolumeClaim:
            claimName: jasper-license-pvc
        # Definition for the keystore PVC
        - name: jasper-keystore
          persistentVolumeClaim:
            claimName: jasper-keystore-pvc
        - name: jasper-customization
          persistentVolumeClaim:
            claimName: jasper-customization-pvc