apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-socket
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: socket
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-socket
    spec:
      containers:
        - name: socket
          image: kmontes2020/medinec-socket:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 7171
              protocol: TCP
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always