apiVersion: v1
kind: Secret
metadata:
  name: jasperreports-secrets
  namespace: medinec
type: Opaque
data:
  DB_HOST: emV1cy1ydy5wb3N0Z3Jlcy1wcm9kLnN2Yy5jbHVzdGVyLmxvY2Fs
  DB_PORT: NTQzMg==
  DB_NAME: amFzcGVy
  DB_USER: bWVkaW5lY19ydw==
  DB_PASS: RUIwdklHNldOT0pMWGQ1bXRqcjdmZGRtQ3ZQOHR4eU4=
  DB_POSTGRES_USER: bWVkaW5lY19ydw==
  DB_POSTGRES_PASS: RUIwdklHNldOT0pMWGQ1bXRqcjdmZGRtQ3ZQOHR4eU4=