apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-patients
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: patients
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-patients
    spec:
      containers:
        - name: patients
          image: kmontes2020/medinec-patients:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9909
              protocol: TCP
          envFrom:
            - secretRef:
                name: patients-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always