apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: kmontes2020/medinec-report:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9908
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: report-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
      imagePullSecrets:
        - name: docker-hub