apiVersion: apps/v1
kind: Deployment
metadata:
  name: shift
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-shift
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: shift
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-shift
    spec:
      containers:
        - name: shift
          image: kmontes2020/medinec-shift:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9908
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: shift-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always