name: ci-config

env:
  SERVICE_NAME: 'config'
  SERVICE_PATH: 'config'

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
    paths:
      - 'config/**'
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            "PACKAGE_TOKEN=${{secrets.PACKAGE_TOKEN}}"
          context: "{{defaultContext}}:${{ env.SERVICE_PATH }}"
          push: true
          tags: kmontes2020/medinec-config:v1
